import Head from 'next/head'
import LandingPage from '../components/landing'

export default function Home() {

    return (
        <>
            <Head>
                <title>Social Net</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LandingPage />
        </>
    )
}